services:
  backend:
    build: ./backend
    environment:
      - JDBC_URL=jdbc:postgresql://host.docker.internal:5432/myfsapp
    ports:
      - "8080:8080"
    network_mode: "bridge"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: ./frontend
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/react-app:/app
      - /app/node_modules
    command: npm start